-- ========================================================
-- BACKUP DATASET DATABASE EDPCtikets - BANK NAGARI
-- Tanggal Backup: 12/8/2026, 05.00.41
-- ========================================================

-- Table: users (10 rows)
INSERT INTO "users" ("id", "username", "nama", "role", "passwordHash", "fotoProfilUrl", "ttdUrl", "isAktif", "createdAt") VALUES ('cmso7dlaw0002unccpx5ecpk0', 'pakde', 'Rian Islami', 'user', '$2b$10$pFjc5p.ZPW6CbVpqa9bYb.niNOl/CBeJ1TKVq9ZEPtNVfGrluoL2W', NULL, NULL, TRUE, '2026-08-11T05:11:35.193Z') ON CONFLICT DO NOTHING;
INSERT INTO "users" ("id", "username", "nama", "role", "passwordHash", "fotoProfilUrl", "ttdUrl", "isAktif", "createdAt") VALUES ('cmso7dlca0003unccx814bldt', 'kurnia', 'Kurnia Fajri', 'user', '$2b$10$jVUgSZ9nhJPj98/dt4.Dc.KMH1MTbo88W.WIBVxOhjOAGsBMgo9eW', NULL, NULL, TRUE, '2026-08-11T05:11:35.242Z') ON CONFLICT DO NOTHING;
INSERT INTO "users" ("id", "username", "nama", "role", "passwordHash", "fotoProfilUrl", "ttdUrl", "isAktif", "createdAt") VALUES ('cmso7dl7u0000uncc5qtqlthp', 'mtr1', 'Afrinaldi', 'user', '$2b$10$lfKzjn97HHimCNykAyuWQ.5BuJKHe6qydMZpIfgSm8YJkUPh8M4Se', NULL, NULL, TRUE, '2026-08-11T05:11:35.081Z') ON CONFLICT DO NOTHING;
INSERT INTO "users" ("id", "username", "nama", "role", "passwordHash", "fotoProfilUrl", "ttdUrl", "isAktif", "createdAt") VALUES ('cmso7dl9h0001unccgemhryz8', 'mtr2', 'Rian Islami Putra', 'user', '$2b$10$bQyGoLbkytjrCnbLmZjZW.fHkgbFpXXUdMvzdfWRwRptcwSZt3.My', NULL, NULL, TRUE, '2026-08-11T05:11:35.142Z') ON CONFLICT DO NOTHING;
INSERT INTO "users" ("id", "username", "nama", "role", "passwordHash", "fotoProfilUrl", "ttdUrl", "isAktif", "createdAt") VALUES ('cmsobylvs0002qz69wgk07h4c', 'mtr3', 'Kurnia Fajri', 'user', '$2b$10$0vWpPojYSrZtMrokCopWxO16.MoUDxGXN8CqvJ/LVHiXQmZ8Fjbqa', NULL, NULL, TRUE, '2026-08-11T07:19:54.185Z') ON CONFLICT DO NOTHING;
INSERT INTO "users" ("id", "username", "nama", "role", "passwordHash", "fotoProfilUrl", "ttdUrl", "isAktif", "createdAt") VALUES ('cmsobylxc0003qz691trhvr2q', 'mtr4', 'Ibnu Sauki', 'user', '$2b$10$dlG83U68.8d5qy8pCYNTEORmedLJ.3ENyl3FXOXPjbtHFdxo75fF2', NULL, NULL, TRUE, '2026-08-11T07:19:54.240Z') ON CONFLICT DO NOTHING;
INSERT INTO "users" ("id", "username", "nama", "role", "passwordHash", "fotoProfilUrl", "ttdUrl", "isAktif", "createdAt") VALUES ('cmsobylys0004qz6917jety4w', 'mtr5', 'Ridho M R', 'user', '$2b$10$kVO/30o.k7K1ZDnWgGDuSutQLodJlHA9foDr9e4wqXOV9YaUi4uBC', NULL, NULL, TRUE, '2026-08-11T07:19:54.293Z') ON CONFLICT DO NOTHING;
INSERT INTO "users" ("id", "username", "nama", "role", "passwordHash", "fotoProfilUrl", "ttdUrl", "isAktif", "createdAt") VALUES ('cmso7dlf30005unccw3by9uur', 'superadmin', 'Super Admin', 'superadmin', '$2b$10$KrXZVx8xci4ekGamCgrZ0enW9iYhrgT8AY06AXoCucW1wH9zDNh4e', NULL, NULL, TRUE, '2026-08-11T05:11:35.344Z') ON CONFLICT DO NOTHING;
INSERT INTO "users" ("id", "username", "nama", "role", "passwordHash", "fotoProfilUrl", "ttdUrl", "isAktif", "createdAt") VALUES ('cmsobym1u0006qz69a9ui1rfc', 'tio', 'Tio Rahmayunda', 'supervisi', '$2b$10$fPyhY.hYzYPzGxjQulhi5u6gxCuKaT/OCEFv5ibpDVBrTNOLp98ci', NULL, NULL, TRUE, '2026-08-11T07:19:54.402Z') ON CONFLICT DO NOTHING;
INSERT INTO "users" ("id", "username", "nama", "role", "passwordHash", "fotoProfilUrl", "ttdUrl", "isAktif", "createdAt") VALUES ('cmso7dldo0004uncc108fj5ry', 'berto', 'Berto L', 'supervisi', '$2b$10$ZoFF48YY1D.kvh6qIsyPDOZEkDZjG.xucTysCCpYBiNXJw50PyHli', NULL, NULL, TRUE, '2026-08-11T05:11:35.293Z') ON CONFLICT DO NOTHING;

-- Table: workstation_master (34 rows)
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlf90006unccz2wj80wc', 'PAYAKUMBUH', '0100', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlfc0007unccnfduueds', 'BUKITTINGGI', '0200', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlfe0008unccs79ibqig', 'BATUSANGKAR', '0300', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlfg0009uncc1s2ahd88', 'SOLOK', '0600', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlfi000aunccmznjdyqr', 'PARIAMAN', '0500', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlfk000buncctgbe6ta8', 'PAINAN', '0400', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlfl000cuncco24d1udj', 'SIJUNJUNG', '0700', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlfo000dunccbafvx1to', 'LUBUK SIKAPING', '0800', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlfr000eunccoqmhqixv', 'PASAR RAYA', '1000', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlft000funccxx7nw2qg', 'SITEBA', '1005', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlfv000guncc0aaiq10h', 'SAWAHLUNTO', '1100', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlfw000hunccgg9qtkxr', 'SIMPANG EMPAT', '1200', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlfy000iunccrp17pm2j', 'MUARA LABUH', '1300', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlg0000juncc5l6md73s', 'LUBUK GADANG', '1301', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlg1000kuncc9ulaggkx', 'KOTO BARU', '1400', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlg2000luncc815fsnj9', 'PULAU PUNJUNG', '1403', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlg4000munccez46fjpj', 'UJUNG GADING', '1500', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlg5000nunccdd0sojj8', 'LUBUK BASUNG', '1600', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlg7000ouncc642ud5xy', 'LUBUK ALUNG', '1700', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlg8000punccyzhsso8h', 'TAPAN', '1900', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlga000quncc6apqdtg0', 'LINTAU', '2000', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlgb000runccdn98bjha', 'CABANG UTAMA', '2100', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlgd000suncce6zyht55', 'MENTAWAI', '2110', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlge000tunccn305lf46', 'TAPUS', '2200', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlgf000uuncc3u4ax9ew', 'ALAHAN PANJANG', '2300', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlgh000vunccb1yv8t01', 'JAKARTA', '2400', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlgi000wuncc8nnkzrus', 'PEKANBARU', '2500', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlgk000xunccgbn77etx', 'BANDUNG', '2600', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlgl000yunccghe21lpx', 'SYARIAH PADANG', '7100', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlgm000zuncc0svoxser', 'SYARIAH SOLOK', '7202', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlgo0010uncc5xqfq7uy', 'SYARIAH PAYAKUMBUH', '7200', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlgp0011uncct1iazour', 'SYARIAH BUKITTINGGI', '7201', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlgr0012uncc2citx435', 'SYARIAH BATUSANGKAR', '7203', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "workstation_master" ("id", "namaCabang", "kodeKantor", "lokasiKantor") VALUES ('cmso7dlgs0013unccihcyhu4f', 'PADANG PANJANG', '0900', NULL) ON CONFLICT DO NOTHING;

-- Tabel tickets: kosong

-- Tabel ticket_activities: kosong

-- Table: server_access_logs (20 rows)
INSERT INTO "server_access_logs" ("id", "namaOrang", "instansi", "namaPic", "keperluan", "jenisAkses", "waktuAkses", "waktuKeluar", "fotoUrl", "ttdUrl", "catatanOleh", "statusApproval", "approvedBy", "createdAt") VALUES ('cmso7dlgx0014uncco9o939mi', 'Hendra Wijaya (Teknisi PLN)', 'PT. PLN (Persero)', 'RUDI HARNO FAZLUR RAHMAN', 'Maintenance Panel Listrik & UPS Server Room', 'masuk', '2026-08-11T03:11:35.407Z', '2026-08-11T04:41:35.407Z', 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOJM9PDkeODFDZCORQGQzOkjDxub78gAAAAAA', NULL, 'cmso7dl7u0000uncc5qtqlthp', 'approved', 'cmso7dldo0004uncc108fj5ry', '2026-08-11T05:11:35.410Z') ON CONFLICT DO NOTHING;
INSERT INTO "server_access_logs" ("id", "namaOrang", "instansi", "namaPic", "keperluan", "jenisAkses", "waktuAkses", "waktuKeluar", "fotoUrl", "ttdUrl", "catatanOleh", "statusApproval", "approvedBy", "createdAt") VALUES ('cmso7dlgx0015uncc604m0yuu', 'Budi Pratama (Vendor AC)', 'PT. Cold Tech Indonesia', 'DIMAS TEGUH PRIBADI', 'Pengecekan Freon & Pembersihan AC Precision Server', 'masuk', '2026-08-11T04:26:35.407Z', NULL, 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOJM9PDkeODFDZCORQGQzOkjDxub78gAAAAAA', NULL, 'cmso7dl7u0000uncc5qtqlthp', 'pending', NULL, '2026-08-11T05:11:35.410Z') ON CONFLICT DO NOTHING;
INSERT INTO "server_access_logs" ("id", "namaOrang", "instansi", "namaPic", "keperluan", "jenisAkses", "waktuAkses", "waktuKeluar", "fotoUrl", "ttdUrl", "catatanOleh", "statusApproval", "approvedBy", "createdAt") VALUES ('cmsobym530008qz69uuj2pkvx', 'Hendra Wijaya (Teknisi PLN)', 'PT. PLN (Persero)', 'RUDI HARNO FAZLUR RAHMAN', 'Maintenance Panel Listrik & UPS Server Room', 'masuk', '2026-08-11T05:19:54.519Z', '2026-08-11T06:49:54.519Z', 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOJM9PDkeODFDZCORQGQzOkjDxub78gAAAAAA', NULL, 'cmso7dlaw0002unccpx5ecpk0', 'approved', 'cmsobym1u0006qz69a9ui1rfc', '2026-08-11T07:19:54.520Z') ON CONFLICT DO NOTHING;
INSERT INTO "server_access_logs" ("id", "namaOrang", "instansi", "namaPic", "keperluan", "jenisAkses", "waktuAkses", "waktuKeluar", "fotoUrl", "ttdUrl", "catatanOleh", "statusApproval", "approvedBy", "createdAt") VALUES ('cmsobym530009qz699msy7kmg', 'Budi Pratama (Vendor AC)', 'PT. Cold Tech Indonesia', 'DIMAS TEGUH PRIBADI', 'Pengecekan Freon & Pembersihan AC Precision Server', 'masuk', '2026-08-11T06:34:54.519Z', NULL, 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOJM9PDkeODFDZCORQGQzOkjDxub78gAAAAAA', NULL, 'cmso7dlaw0002unccpx5ecpk0', 'pending', NULL, '2026-08-11T07:19:54.520Z') ON CONFLICT DO NOTHING;
INSERT INTO "server_access_logs" ("id", "namaOrang", "instansi", "namaPic", "keperluan", "jenisAkses", "waktuAkses", "waktuKeluar", "fotoUrl", "ttdUrl", "catatanOleh", "statusApproval", "approvedBy", "createdAt") VALUES ('cmsobz7nh0008une4a61dydzt', 'Hendra Wijaya (Teknisi PLN)', 'PT. PLN (Persero)', 'RUDI HARNO FAZLUR RAHMAN', 'Maintenance Panel Listrik & UPS Server Room', 'masuk', '2026-08-11T05:20:22.396Z', '2026-08-11T06:50:22.396Z', 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOJM9PDkeODFDZCORQGQzOkjDxub78gAAAAAA', NULL, 'cmso7dlaw0002unccpx5ecpk0', 'approved', 'cmsobym1u0006qz69a9ui1rfc', '2026-08-11T07:20:22.398Z') ON CONFLICT DO NOTHING;
INSERT INTO "server_access_logs" ("id", "namaOrang", "instansi", "namaPic", "keperluan", "jenisAkses", "waktuAkses", "waktuKeluar", "fotoUrl", "ttdUrl", "catatanOleh", "statusApproval", "approvedBy", "createdAt") VALUES ('cmsobz7ni0009une4xbkfade9', 'Budi Pratama (Vendor AC)', 'PT. Cold Tech Indonesia', 'DIMAS TEGUH PRIBADI', 'Pengecekan Freon & Pembersihan AC Precision Server', 'masuk', '2026-08-11T06:35:22.396Z', NULL, 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOJM9PDkeODFDZCORQGQzOkjDxub78gAAAAAA', NULL, 'cmso7dlaw0002unccpx5ecpk0', 'pending', NULL, '2026-08-11T07:20:22.398Z') ON CONFLICT DO NOTHING;
INSERT INTO "server_access_logs" ("id", "namaOrang", "instansi", "namaPic", "keperluan", "jenisAkses", "waktuAkses", "waktuKeluar", "fotoUrl", "ttdUrl", "catatanOleh", "statusApproval", "approvedBy", "createdAt") VALUES ('cmspibq900008qz694itfnpik', 'Hendra Wijaya (Teknisi PLN)', 'PT. PLN (Persero)', 'RUDI HARNO FAZLUR RAHMAN', 'Maintenance Panel Listrik & UPS Server Room', 'masuk', '2026-08-12T01:05:50.243Z', '2026-08-12T02:35:50.243Z', 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOJM9PDkeODFDZCORQGQzOkjDxub78gAAAAAA', NULL, 'cmso7dlaw0002unccpx5ecpk0', 'approved', 'cmsobym1u0006qz69a9ui1rfc', '2026-08-12T03:05:50.244Z') ON CONFLICT DO NOTHING;
INSERT INTO "server_access_logs" ("id", "namaOrang", "instansi", "namaPic", "keperluan", "jenisAkses", "waktuAkses", "waktuKeluar", "fotoUrl", "ttdUrl", "catatanOleh", "statusApproval", "approvedBy", "createdAt") VALUES ('cmspibq900009qz69iupz3mgn', 'Budi Pratama (Vendor AC)', 'PT. Cold Tech Indonesia', 'DIMAS TEGUH PRIBADI', 'Pengecekan Freon & Pembersihan AC Precision Server', 'masuk', '2026-08-12T02:20:50.243Z', NULL, 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOJM9PDkeODFDZCORQGQzOkjDxub78gAAAAAA', NULL, 'cmso7dlaw0002unccpx5ecpk0', 'pending', NULL, '2026-08-12T03:05:50.244Z') ON CONFLICT DO NOTHING;
INSERT INTO "server_access_logs" ("id", "namaOrang", "instansi", "namaPic", "keperluan", "jenisAkses", "waktuAkses", "waktuKeluar", "fotoUrl", "ttdUrl", "catatanOleh", "statusApproval", "approvedBy", "createdAt") VALUES ('cmspjtu090008o369p9ab7ksi', 'Hendra Wijaya (Teknisi PLN)', 'PT. PLN (Persero)', 'RUDI HARNO FAZLUR RAHMAN', 'Maintenance Panel Listrik & UPS Server Room', 'masuk', '2026-08-12T01:47:54.536Z', '2026-08-12T03:17:54.536Z', 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOJM9PDkeODFDZCORQGQzOkjDxub78gAAAAAA', NULL, 'cmso7dlaw0002unccpx5ecpk0', 'approved', 'cmsobym1u0006qz69a9ui1rfc', '2026-08-12T03:47:54.537Z') ON CONFLICT DO NOTHING;
INSERT INTO "server_access_logs" ("id", "namaOrang", "instansi", "namaPic", "keperluan", "jenisAkses", "waktuAkses", "waktuKeluar", "fotoUrl", "ttdUrl", "catatanOleh", "statusApproval", "approvedBy", "createdAt") VALUES ('cmspjtu090009o3693yx1yck8', 'Budi Pratama (Vendor AC)', 'PT. Cold Tech Indonesia', 'DIMAS TEGUH PRIBADI', 'Pengecekan Freon & Pembersihan AC Precision Server', 'masuk', '2026-08-12T03:02:54.536Z', NULL, 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOJM9PDkeODFDZCORQGQzOkjDxub78gAAAAAA', NULL, 'cmso7dlaw0002unccpx5ecpk0', 'pending', NULL, '2026-08-12T03:47:54.537Z') ON CONFLICT DO NOTHING;
INSERT INTO "server_access_logs" ("id", "namaOrang", "instansi", "namaPic", "keperluan", "jenisAkses", "waktuAkses", "waktuKeluar", "fotoUrl", "ttdUrl", "catatanOleh", "statusApproval", "approvedBy", "createdAt") VALUES ('cmspjxzry0008unssnk8j7jtu', 'Hendra Wijaya (Teknisi PLN)', 'PT. PLN (Persero)', 'RUDI HARNO FAZLUR RAHMAN', 'Maintenance Panel Listrik & UPS Server Room', 'masuk', '2026-08-12T01:51:08.631Z', '2026-08-12T03:21:08.631Z', 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOJM9PDkeODFDZCORQGQzOkjDxub78gAAAAAA', NULL, 'cmso7dlaw0002unccpx5ecpk0', 'approved', 'cmsobym1u0006qz69a9ui1rfc', '2026-08-12T03:51:08.638Z') ON CONFLICT DO NOTHING;
INSERT INTO "server_access_logs" ("id", "namaOrang", "instansi", "namaPic", "keperluan", "jenisAkses", "waktuAkses", "waktuKeluar", "fotoUrl", "ttdUrl", "catatanOleh", "statusApproval", "approvedBy", "createdAt") VALUES ('cmspjxzry0009unssrqruvw0o', 'Budi Pratama (Vendor AC)', 'PT. Cold Tech Indonesia', 'DIMAS TEGUH PRIBADI', 'Pengecekan Freon & Pembersihan AC Precision Server', 'masuk', '2026-08-12T03:06:08.631Z', NULL, 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOJM9PDkeODFDZCORQGQzOkjDxub78gAAAAAA', NULL, 'cmso7dlaw0002unccpx5ecpk0', 'pending', NULL, '2026-08-12T03:51:08.638Z') ON CONFLICT DO NOTHING;
INSERT INTO "server_access_logs" ("id", "namaOrang", "instansi", "namaPic", "keperluan", "jenisAkses", "waktuAkses", "waktuKeluar", "fotoUrl", "ttdUrl", "catatanOleh", "statusApproval", "approvedBy", "createdAt") VALUES ('cmspl8arh0008mw69a2054q6m', 'Hendra Wijaya (Teknisi PLN)', 'PT. PLN (Persero)', 'RUDI HARNO FAZLUR RAHMAN', 'Maintenance Panel Listrik & UPS Server Room', 'masuk', '2026-08-12T02:27:09.052Z', '2026-08-12T03:57:09.052Z', 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOJM9PDkeODFDZCORQGQzOkjDxub78gAAAAAA', NULL, 'cmso7dlaw0002unccpx5ecpk0', 'approved', 'cmsobym1u0006qz69a9ui1rfc', '2026-08-12T04:27:09.053Z') ON CONFLICT DO NOTHING;
INSERT INTO "server_access_logs" ("id", "namaOrang", "instansi", "namaPic", "keperluan", "jenisAkses", "waktuAkses", "waktuKeluar", "fotoUrl", "ttdUrl", "catatanOleh", "statusApproval", "approvedBy", "createdAt") VALUES ('cmspl8arh0009mw69tvg7tpqr', 'Budi Pratama (Vendor AC)', 'PT. Cold Tech Indonesia', 'DIMAS TEGUH PRIBADI', 'Pengecekan Freon & Pembersihan AC Precision Server', 'masuk', '2026-08-12T03:42:09.052Z', NULL, 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOJM9PDkeODFDZCORQGQzOkjDxub78gAAAAAA', NULL, 'cmso7dlaw0002unccpx5ecpk0', 'pending', NULL, '2026-08-12T04:27:09.053Z') ON CONFLICT DO NOTHING;
INSERT INTO "server_access_logs" ("id", "namaOrang", "instansi", "namaPic", "keperluan", "jenisAkses", "waktuAkses", "waktuKeluar", "fotoUrl", "ttdUrl", "catatanOleh", "statusApproval", "approvedBy", "createdAt") VALUES ('cmspl9nyj0008jz6ajtrva8xu', 'Hendra Wijaya (Teknisi PLN)', 'PT. PLN (Persero)', 'RUDI HARNO FAZLUR RAHMAN', 'Maintenance Panel Listrik & UPS Server Room', 'masuk', '2026-08-12T02:28:12.810Z', '2026-08-12T03:58:12.810Z', 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOJM9PDkeODFDZCORQGQzOkjDxub78gAAAAAA', NULL, 'cmso7dlaw0002unccpx5ecpk0', 'approved', 'cmsobym1u0006qz69a9ui1rfc', '2026-08-12T04:28:12.811Z') ON CONFLICT DO NOTHING;
INSERT INTO "server_access_logs" ("id", "namaOrang", "instansi", "namaPic", "keperluan", "jenisAkses", "waktuAkses", "waktuKeluar", "fotoUrl", "ttdUrl", "catatanOleh", "statusApproval", "approvedBy", "createdAt") VALUES ('cmspl9nyj0009jz6augmg3xsz', 'Budi Pratama (Vendor AC)', 'PT. Cold Tech Indonesia', 'DIMAS TEGUH PRIBADI', 'Pengecekan Freon & Pembersihan AC Precision Server', 'masuk', '2026-08-12T03:43:12.810Z', NULL, 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOJM9PDkeODFDZCORQGQzOkjDxub78gAAAAAA', NULL, 'cmso7dlaw0002unccpx5ecpk0', 'pending', NULL, '2026-08-12T04:28:12.811Z') ON CONFLICT DO NOTHING;
INSERT INTO "server_access_logs" ("id", "namaOrang", "instansi", "namaPic", "keperluan", "jenisAkses", "waktuAkses", "waktuKeluar", "fotoUrl", "ttdUrl", "catatanOleh", "statusApproval", "approvedBy", "createdAt") VALUES ('cmsplyz110008o4698opmctwk', 'Hendra Wijaya (Teknisi PLN)', 'PT. PLN (Persero)', 'RUDI HARNO FAZLUR RAHMAN', 'Maintenance Panel Listrik & UPS Server Room', 'masuk', '2026-08-12T02:47:53.556Z', '2026-08-12T04:17:53.556Z', 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOJM9PDkeODFDZCORQGQzOkjDxub78gAAAAAA', NULL, 'cmso7dlaw0002unccpx5ecpk0', 'approved', 'cmsobym1u0006qz69a9ui1rfc', '2026-08-12T04:47:53.557Z') ON CONFLICT DO NOTHING;
INSERT INTO "server_access_logs" ("id", "namaOrang", "instansi", "namaPic", "keperluan", "jenisAkses", "waktuAkses", "waktuKeluar", "fotoUrl", "ttdUrl", "catatanOleh", "statusApproval", "approvedBy", "createdAt") VALUES ('cmsplyz110009o469zqha9ucc', 'Budi Pratama (Vendor AC)', 'PT. Cold Tech Indonesia', 'DIMAS TEGUH PRIBADI', 'Pengecekan Freon & Pembersihan AC Precision Server', 'masuk', '2026-08-12T04:02:53.556Z', NULL, 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOJM9PDkeODFDZCORQGQzOkjDxub78gAAAAAA', NULL, 'cmso7dlaw0002unccpx5ecpk0', 'pending', NULL, '2026-08-12T04:47:53.557Z') ON CONFLICT DO NOTHING;
INSERT INTO "server_access_logs" ("id", "namaOrang", "instansi", "namaPic", "keperluan", "jenisAkses", "waktuAkses", "waktuKeluar", "fotoUrl", "ttdUrl", "catatanOleh", "statusApproval", "approvedBy", "createdAt") VALUES ('cmspmdzv20008o5695iaeznt8', 'Hendra Wijaya (Teknisi PLN)', 'PT. PLN (Persero)', 'RUDI HARNO FAZLUR RAHMAN', 'Maintenance Panel Listrik & UPS Server Room', 'masuk', '2026-08-12T02:59:34.478Z', '2026-08-12T04:29:34.478Z', 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOJM9PDkeODFDZCORQGQzOkjDxub78gAAAAAA', NULL, 'cmso7dlaw0002unccpx5ecpk0', 'approved', 'cmsobym1u0006qz69a9ui1rfc', '2026-08-12T04:59:34.479Z') ON CONFLICT DO NOTHING;
INSERT INTO "server_access_logs" ("id", "namaOrang", "instansi", "namaPic", "keperluan", "jenisAkses", "waktuAkses", "waktuKeluar", "fotoUrl", "ttdUrl", "catatanOleh", "statusApproval", "approvedBy", "createdAt") VALUES ('cmspmdzv20009o5691cji54da', 'Budi Pratama (Vendor AC)', 'PT. Cold Tech Indonesia', 'DIMAS TEGUH PRIBADI', 'Pengecekan Freon & Pembersihan AC Precision Server', 'masuk', '2026-08-12T04:14:34.478Z', NULL, 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOJM9PDkeODFDZCORQGQzOkjDxub78gAAAAAA', NULL, 'cmso7dlaw0002unccpx5ecpk0', 'pending', NULL, '2026-08-12T04:59:34.479Z') ON CONFLICT DO NOTHING;

